project:
  type: website

website:
  title: "Página personal"
  navbar:
    left:
      - courses/index.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
