project:
  type: website

website:
  title: "Página personal"
  navbar:
    left:
      - courses/index.qmd

  sidebar:
    - title: "Cursos"
      style: "docked"
      contents:
      - section: "2024"
        href: courses/index.qmd
        contents:
          - courses/4302.0.qmd
          - courses/3002.0.qmd
          - courses/3501.0.qmd

format:
  html:
    theme: morph
    css: styles.css

execute:
  freeze: auto
