project:
  type: website

website:
  title: "Vicente González"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
